#+TITLE: Release of Aquamacs 4 alpha - version 3.9.1
#+URL: /aquamacs-4-alpha

The alpha release of Aquamacs 4 is now available ([[https://aquamacs.s3.us-east-2.amazonaws.com/Aquamacs-alpha.app.tgz][download]])

Aquamacs 4 is a big jump in the underlying version of Emacs, with little change in the Aquamacs-specific aspects that differ from Emacs. This alpha version is based on Emacs version 29.4, the current released version of Emacs.

Feedback on this release is very valuable for finding problems, since no one individual uses all the different features in Aquamacs.

In this case, "alpha" means a release that may have serious bugs, use at your own risk!

The internal version number for the alpha release is 3.9.1, because of the way Aquamacs code parses version numbers. In this way, the final release of Aquamacs 4 will be reported as 4.0.

Please report any problems by email to aquamacs-bugs@aquamacs.org, or on github at https://github.com/aquamacs-emacs/aquamacs-emacs/issues.

* Hardware and operating system support

This version of Aquamacs is distributed as a universal binary, including compiled code for both Apple Silicon (ARM) processors and older Intel Macs. It should run on any version of Mac OS since 10.15 (Monterey), which was released in 2021.

This version also includes native library support for the image formats JPEG, SVG, and webp, as well as GNUTLS, libxml2, and JSON.

* Configuration notes

In this alpha release, Aquamacs uses the directory ~~/Library/Preferences/Aquamacs Emacs beta~ for preferences, including downloaded packages from ELPA and MELPA, instead of the usual ~~/Library/Preferences/Aquamacs Emacs~. This is to keep the older Aquamacs data safe if you want to try using Aquamacs-alpha with the option to switch back to Aquamacs 3.6. You might want to copy over the files from ~~/Library/Preferences/Aquamacs Emacs~ to the new directory to start things off, particularly ~Preferences.el~ and ~customizations.el~, along with the ~Packages~ directory if you use it.

If you are using Mac OS 15 (Sequoia), you may get an error that the Aquamacs-alpha application is damaged and should be moved to the trash. In that case, you can use the Terminal to run the command:
#+BEGIN_EXAMPLE
xattr -c Aquamacs-alpha.app
#+END_EXAMPLE
(with the appropriate pathname or current directory, of course). The alpha release has not been through the full application release process that Apple has, and Sequoia tightened up the requirements for it.

* Background on what has changed in Emacs
Emacs has evolved quite a bit since Aquamacs last synced up with the main code. The following links summarize some of the most interesting changes in version 27, 28, and 29:

- [[https://www.masteringemacs.org/article/whats-new-in-emacs-27-1][What's New in Emacs 27.1?]]
- [[https://www.masteringemacs.org/article/whats-new-in-emacs-28-1][What's New in Emacs 28.1?]]
- [[https://www.masteringemacs.org/article/whats-new-in-emacs-29-1][What's New in Emacs 29.1?]]

Thanks to Mickey Peterson for sharing those over time!

* Known problems:

- Some of the menus are not working correctly
- The spelling support is flaky. Sometimes, ispell and flyspell seem to work, and sometimes, they don't.
- auto-revert mysteriously doesn't always revert automatically
- Clicking tabs opens panel with help (not always, but most of the time)
- Setting font for e.g. LaTeX mode does work (void-function ns-popup-font-panel)
- Saving options doesn't work: (void-variable global-linum-mode)
- Copying the preferences may not correctly copy font and keyboard settings
- The edit and right-click menus are incorrect
- Modifier keys are displayed represented by letter (Emacs-style) instead of symbol (Aquamacs-style)
- js-json count words crashes the application

Other known problems with Aquamacs are in the GitHub issue tracker for the project at [[https://github.com/aquamacs-emacs/aquamacs-emacs/issues][Aquamacs issues]].

* Upcoming releases
There is likely to be an "alpha 2" release after getting some feedback from the community, followed by a larger beta release.

Aquamacs 4 will be released based on the current Emacs 29.4 code, and Aquamacs 4.1 will likely follow sometime after Emacs 30 is released.
