#+TITLE: Release of Aquamacs 4 alpha 2
#+URL: /aquamacs-4-alpha

The second alpha release of Aquamacs 4 ("alpha 2") is now available ([[https://aquamacs.s3.us-east-2.amazonaws.com/Aquamacs-alpha2.zip][download]]), and these are the release notes for it, as of April 2026.

Aquamacs 4 is a big jump in the underlying version of Emacs, with little change in the Aquamacs-specific aspects that differ from Emacs. This alpha2 version is based on Emacs version 29.4. This version is called "alpha2" because there was previous alpha-level release, but it required more work before even a broader alpha releas was possible.

Feedback on this release is very valuable for finding problems, since no one individual uses all the different features in Aquamacs. As an alpha version, it may have serious bugs, so use at your own risk!

The internal version number for the alpha release is 3.9.2, because of the way Aquamacs code parses version numbers. The final release of Aquamacs 4 will be reported as 4.0.

Please report any problems by email to aquamacs-bugs@aquamacs.org, or on github at [[https://github.com/aquamacs-emacs/aquamacs-emacs/issues][https://github.com/aquamacs-emacs/aquamacs-emacs/issues]].

* Important changes
The first time Aquamacs 4 starts up, it may seem a little slow, as explained here.

Upgrading to a new version of Emacs means that many packages and customization changes are different.

To make it possible for you to switch back to the current version (Aquamacs 3.6) or even run them at the same time, Aquamacs 4 is changing the Preferences directory to

"~/Library/Preferences/Aquamacs Emacs 4"

instead of the previous

"~/Library/Preferences/Aquamacs Emacs"

(quotes used because of the spaces in the filename)

The Preferences directory is copied automatically the first time Aquamacs 4 runs. They are not synced in any way after that, however. Depending on the size of the Preferences directory, it may take a little while to run and seem a little slow to start.

* Hardware and operating system support

This version of Aquamacs is distributed as a universal binary, including compiled code for both Apple Silicon (ARM) processors and older Intel Macs. It should run on any version of Mac OS since 10.15 (Monterey), which was released in 2021.

This version also includes native library support for the image formats JPEG, PNG, TIFF, GIF, and webp, as well as GNUTLS, libxml2, JSON, and sqlite3.

* Background on what has changed in Emacs
Emacs has evolved quite a bit since Aquamacs last synced up with the main code.

There is more detail in the official announcements of those versions.
To get a sense of what's changed, you can read about the changes in Emacs at https://www.gnu.org/software/emacs/manual/html_node/efaq/History-of-Emacs.html, for Emacs 26, 27, 28, and 29. (Yes, it's a lot!)

The following links summarize some of the most interesting changes in version 27, 28, and 29:

- [[https://www.masteringemacs.org/article/whats-new-in-emacs-27-1][What's New in Emacs 27.1?]]
- [[https://www.masteringemacs.org/article/whats-new-in-emacs-28-1][What's New in Emacs 28.1?]]
- [[https://www.masteringemacs.org/article/whats-new-in-emacs-29-1][What's New in Emacs 29.1?]]

Thanks to Mickey Peterson for sharing those over time!

* Some larger changes

Aquamacs previously included a bundled version of python-mode. It has been removed in favor of the one now built in to Emacs. The previously-bundled python-mode.el  is available via the python-mode package in MELPA, so it's easy to add back now if you prefer. The source code for it is maintained at https://gitlab.com/groups/python-mode-devs.

* Some known problems
Some of the known problems in this release include:

- Printing directly from Aquamacs does not work reliably. Printing from LaTeX using AUCTeX should works fine, as should printing documents from Org export. This is a high-priority bug to fix for the upcoming beta release.
- Some of the menus are not working correctly
- auto-revert mysteriously doesn't always revert automatically
- Clicking tabs opens panel with help (not always, but most of the time)
- Setting font for e.g. LaTeX mode does work (void-function ns-popup-font-panel)
- Saving options doesn't work: (void-variable global-linum-mode)
- Copying the preferences may not correctly copy font and keyboard settings
- The edit and right-click menus are incorrect
- Modifier keys are displayed represented by letter (Emacs-style) instead of symbol (Aquamacs-style)
- js-json count words crashes the application

Other known problems with Aquamacs are in the GitHub issue tracker for the project at [[https://github.com/aquamacs-emacs/aquamacs-emacs/issues][Aquamacs issues]].

* Upcoming releases

A full beta release of Aquamacs 4 will be available after we get some feedback about problems in the alpha2 release.

The full version of Aquamacs 4 will be released based on the Emacs 29.4 code, with immediate work to follow to update Aquamacs to be based on Emacs 30 or 31, depending on timing.
