#+TITLE: Reporting problems with Aquamacs
#+URL: /reporting-bugs
#+ALIASES[]: /reporting-bugs.html

* Reporting problems with Aquamacs

Bug reports are sent to the [[mailto:aquamacs-bugs@aquamacs.org][Aquamacs-bugs mailbox]] using the "Send Bug Report" function in the Aquamacs /Help / Diagnose and Report Bug/ menu. If you have a problem with a particular mode and you're sure that the bug occurs when using that mode with a plain GNU Emacs (not
Aquamacs), then try to get in touch with the developers of that mode. Do not send bug reports to the Emacs on OS X mailing list. If you know that the bug occurs in GNU Emacs, too, then report it to the [[mailto:bug-gnu-emacs@gnu.org][GNU Emacs Bug mailing list]] instead. However you submit a bug, you must follow the points below before making a report!

** Bug Reporting Procedure:
If you encounter a bug while using a nightly build, you must run the
following checks to determine the general source of the bug:

1. Ensure you're using the latest [[/downloads.html][release]] or a
   recent [[file:nightlies.html][nightly build]].
2. Start Aquamacs without customizations: In the Help menu, find
   /Diagnose and Report Bugs/ / /Start Aquamacs without customizations/.
   A new Aquamacs will open, with default settings. Can you reproduce
   the problem here? If so, the steps needed to reproduce should go into
   your bug report. If you can't reproduce, have a look at your personal
   settings. The bug is either in the settings, or it is triggered by
   them.
3. Is the bug still there, even when running Aquamacs Emacs without your
   customizations? If not, have a look at your customizations in
   Preferences.el, .emacs, the Plugins and other files in
   Library/Application Support/Aquamacs Emacs/ (both in your user
   directory and in the system-wide /Library directory). Please identify
   the settings that cause the problem and report them to us if you find
   that Aquamacs is at fault.

Your bug reports will be archived and publicly accessible. We read every
bug report, although we are unable to respond to all of them.
Update regularly. Consider using the [[file:nightlies.html][nightly
builds from the source code repository]].
